# Disable sudo to speed up the build
sudo: false
# Set the build language to Python
language: python
python:
  - "3.10"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
  - pip install pytest-pylint
  - pip install pylint
# command to run tests
script:
  - pytest --cov=ClustPy --pylint
# Codecov
after_success:
    - codecov