general:
    save_path: "results"
dataset:
    preprocessing:
         - normalize
    percentages: [0.0, 0.3, 0.5, 0.7,  1.0]
    transform:
    train_test_split: True
    list_of_datasets:
        - mnist:
              transforms:
                  - normalize:
autoencoder:
    - feed_forward:
        layers: [784, 512, 256, 10]
        optimizer_params:
            lr: 0.001
        n_epochs: 1
algorithm:
    - acedec:
        params:
            n_clusters: [10,1]
            debug: False
            pretrain_learning_rate: 0.0001
            pretrain_epochs: 1
            clustering_learning_rate: 0.001
            clustering_epochs: 1
            print_step: 50
            recluster: True
            init: "acedec"
            cluster_assignment: "acedec"
            reclustering: "acedec"
            update_cluster: "acedec"
            loss_calculation: "acedec"
            prediction: "acedec"
            prediction_kwargs:
                alpha: 0.5
metric:
    - NMI
    - ARI
evaluation:
    n_repetitions: 5
    aggregation_functions:
        - np.mean
    add_runtinme: True
    add_n_clusters: False
    save_intermediatie_results: True