path_to_pretrained_autoencoders: ".../"
datasets: ["MNIST"]
evaluation: ["NMI", "ARI", "ACC"]
architecture: ["CNN"]
n_clusters: None
batch_size: batch_size
clustering_epochs: n_clustering_epochs
optimizer_class: optimizer_class
init_subsample_size: 10000
clustering_optimizer_params: {"lr": 5e-4}
loss_fn: loss_fn
embedding_size: embedding_size
augmentation_invariance: augmentation
